version: 2
updates:
  - package-ecosystem: "pip"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "jmelot"

  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/supply-chain"
    schedule:
      interval: "monthly"
    reviewers:
      - "brianlove"
    ignore:
      - dependency-name: "@eto*"
      - dependency-name: "@mdx-js*"
      - dependency-name: "gatsby*"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "brianlove"
